"""add sentiment_score

Revision ID: ce0dcdb48a65
Revises: c326dc7af4d9
Create Date: 2025-05-11 01:49:54.400922

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce0dcdb48a65'
down_revision: Union[str, None] = 'c326dc7af4d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 1) サーバーデフォルトで既存行に 0.0 をセットしつつ NOT NULL カラム追加
    op.add_column(
        'journal_entries',
        sa.Column(
            'sentiment_score',
            sa.Float(),
            nullable=False,
            server_default="0.0"
        )
    )
    # 2) 以降はコード側で必ず値を設定するので、DB側のデフォルトは外す
    op.alter_column(
        'journal_entries',
        'sentiment_score',
        server_default=None
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('journal_entries', 'sentiment_score')
    # ### end Alembic commands ###
